### PR TITLE
Capstone project: Swipex App

### PR DESCRIPTION
**Pull request by kirokoNjenga**
*What does this PR do*
-Html and CSS web application base on the UI given by Microverse.
-Html code has used all require semantic tags
-In the project, I have used vanilla CSS3 using flexbox, margin and paddings to place elements
-The project is fully responsive with a Native Mobile app feeling in small screens
-Applied front-end best practice with help w3c validator and Stylelint
-followed the UI design given as per the project requirement

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
### Good job guys, this was amazing, however, you have a few changes to make for your project to be approved.

- work on responsiveness to fit different screen sizes i.e mobile, tablet and laptop. See how to arrange content on such screen

Once you have made all these changes, resubmit your project for review. I wish you all the best

**Comment by kirokoNjenga** [comment]
@rOluochKe  i don't think 🤔 you took time to check my project, the web app is responsive to all screens  am using my mobile phone attached are mobile screenshot of the three, pages
 
Screenshot_2020-01-28-08-47-14-35
Screenshot_2020-01-28-08-47-32-44
Screenshot_2020-01-28-08-47-44-43

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review by Tolulope Olusakin(TSE)
Currently writing your project review, please check on it in the next 2 hours for some feedback

**Comment by kirokoNjenga** [comment]
-added changes requested by(TSE)
image

**Review by nikasulo — CHANGES_REQUESTED** [review]
# This is really beautiful work @Samkiroko and @rOluochKe! :handshake: 
Please take a look at the following screenshots in connection with the responsiveness issue brought up by the previous TSE.

At 1024px
screenshot

At 768px
screenshot

At 320px
screenshot

Please notice that at 1024px, the design breaks completely. Also take not of the footer at 768px and below. Consider making appropriate changes before your next review request so your project can be approved! I wish you all the best :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by kirokoNjenga** [comment]
-working perfectly fine 
Screenshot_2020-01-28-12-42-04-32

**Review by nikasulo — APPROVED** [review]
# Congratulations @Samkiroko!
Please merge and keep moving forward! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
